mincit/urls.py
from django.conf.urls import url

from mincit import views

app_name = 'mincit'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^index/$', views.InicioListViews.as_view(), name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^diagnostico_emp/(\d+)/$',
        views.DiagnosticoEmpresaListViews.as_view(),
        name='diagnostico_emp'),
    url(r'^diagnostico_emp/(\d+)/crear/$',
        views.DiagnosticoEmpresaCreateViews.as_view(),
        name='diagnostico_empresa_crear'),
    url(r'^diagnostico_emp/editar/(?P<id_diagnostico>\d+)/$',
        views.DiagnosticoEmpresaUpdateViews.as_view(),
        name='editar_diagnostico'),
    url(r'^diagnostico_emp/informacion/(\d+)/$',
        views.InformacionViews.as_view(),
        name='informacion'),
    url(r'^diagnostico_emp/informacion/crear/(\d+)/$',
        views.InformacionCreateViews.as_view(),
        name='crear_informacion'),
    url(r'^diagnostico_emp/informacion/editar/(?P<id_informacion>\d+)/$',
        views.InformacionUpdateViews.as_view(),
        name='editar_informacion'),
    url(r'^diagnostico_emp/situacion/(?P<id_diagnostico>\d+)/$',
        views.SituacionViews.as_view(),
        name='situacion'),
    url(r'^diagnostico_emp/situacion/crear/(?P<id_diagnostico>\d+)/$',
        views.SituacionCreateViews.as_view(),
        name='crear_situacion'),
    url(r'^diagnostico_emp/situacion/editar/(?P<id_situacion>\d+)/$',
        views.SituacionUpdateViews.as_view(),
        name='editar_situacion'),
    url(r'^diagnostico_emp/planeacion/(?P<id_diagnostico>\d+)/$',
        views.PlaneacionViews.as_view(),
        name='planeacion'),
    url(r'^diagnostico_emp/planeacion/crear/(?P<id_diagnostico>\d+)/$',
        views.PlaneacionCreateViews.as_view(),
        name='crear_planeacion'),
    url(r'^diagnostico_emp/planeacion/editar/(?P<id_planeacion>\d+)/$',
        views.PlaneacionUpdateViews.as_view(),
        name='editar_planeacion'),
    url(r'^diagnostico_emp/organizacion/(?P<id_diagnostico>\d+)/$',
        views.OrganizacionViews.as_view(),
        name='organizacion'),
    url(r'^diagnostico_emp/organizacion/crear/(?P<id_diagnostico>\d+)/$',
        views.OrganizacionCreateViews.as_view(),
        name='crear_organizacion'),
    url(r'^diagnostico_emp/organizacion/editar/(?P<id_organizacion>\d+)/$',
        views.OrganizacionUpdateViews.as_view(),
        name='editar_organizacion'),
    url(r'^diagnostico_emp/direccion/(?P<id_diagnostico>\d+)/$',
        views.DireccionViews.as_view(),
        name='direccion'),
    url(r'^diagnostico_emp/direccion/crear/(?P<id_diagnostico>\d+)/$',
        views.DireccionCreateViews.as_view(),
        name='crear_direccion'),
    url(r'^diagnostico_emp/direccion/editar/(?P<id_direccion>\d+)/$',
        views.DireccionUpdateViews.as_view(),
        name='editar_direccion'),
    url(r'^diagnostico_emp/control/(?P<id_diagnostico>\d+)/$',
        views.ControlViews.as_view(),
        name='control'),
    url(r'^diagnostico_emp/control/crear/(?P<id_diagnostico>\d+)/$',
        views.ControlCreateViews.as_view(),
        name='crear_control'),
    url(r'^diagnostico_emp/control/editar/(?P<id_control>\d+)/$',
        views.ControlUpdateViews.as_view(),
        name='editar_control'),
    url(r'^diagnostico_emp/recursos/(?P<id_diagnostico>\d+)/$',
        views.RecursoViews.as_view(),
        name='recursos'),
    url(r'^diagnostico_emp/recursos/crear/(?P<id_diagnostico>\d+)/$',
        views.RecursoCreateViews.as_view(),
        name='crear_recursos'),
    url(r'^diagnostico_emp/recursos/editar/(?P<id_recurso>\d+)/$',
        views.RecursoUpdateViews.as_view(),
        name='editar_recursos'),
    url(r'^diagnostico_emp/mercadeo/(?P<id_diagnostico>\d+)/$',
        views.MercadeoViews.as_view(),
        name='mercadeo'),
    url(r'^diagnostico_emp/mercadeo/crear/(?P<id_diagnostico>\d+)/$',
        views.MercadeoCreateViews.as_view(),
        name='crear_mercadeo'),
    url(r'^diagnostico_emp/mercadeo/editar/(?P<id_mercadeo>\d+)/$',
        views.MercadeoUpdateViews.as_view(),
        name='editar_mercadeo'),
    url(r'^diagnostico_emp/financiera/(?P<id_diagnostico>\d+)/$',
        views.FinancieraViews.as_view(),
        name='financiera'),
    url(r'^diagnostico_emp/financiera/crear/(?P<id_diagnostico>\d+)/$',
        views.FinancieraCreateViews.as_view(),
        name='crear_financiera'),
    url(r'^diagnostico_emp/financiera/editar/(?P<id_financiera>\d+)/$',
        views.FinancieraUpdateViews.as_view(),
        name='editar_financiera'),
    url(r'^diagnostico_emp/produccion/(?P<id_diagnostico>\d+)/$',
        views.ProduccionViews.as_view(),
        name='produccion'),
    url(r'^diagnostico_emp/produccion/crear/(?P<id_diagnostico>\d+)/$',
        views.ProduccionCreateViews.as_view(),
        name='crear_produccion'),
    url(r'^diagnostico_emp/produccion/editar/(?P<id_produccion>\d+)/$',
        views.ProduccionUpdateViews.as_view(),
        name='editar_produccion'),
    url(r'^diagnostico_emp/internacionalizacion/(?P<id_diagnostico>\d+)/$',
        views.InternacionalizacionViews.as_view(),
        name='internacionalizacion'),
    url(r'^diagnostico_emp/internacionalizacion/crear/(?P<id_diagnostico>\d+)/$',
        views.InternacionalizacionCreateViews.as_view(),
        name='crear_internacionalizacion'),
    url(r'^diagnostico_emp/internacionalizacion/editar/(?P<id_internacionalizacion>\d+)/$',
        views.InternacionalizacionUpdateViews.as_view(),
        name='editar_internacionalizacion'),


]

urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^mincit/', include('mincit.urls')),

]

mincit/views.py
from __future__ import print_function
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import response
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls.base import reverse
from django.views.generic import View, CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from mincit.forms import LoginForm, InformacionForm, SituacionForm, \
    PlaneacionForm, DiagnosticoEmpresaForm, \
    OrganizacionForm, DireccionForm, ControlForm, RecursoForm, FinancieraForm, \
    MercadeoForm, ProduccionForm, InternacionalizacionForm
from mincit.models import Control, Recurso, Financiera, Mercadeo, Produccion, \
    Internacionalizacion
from models import Empresa, Informacion, DiagnosticoEmpresa, Situacion, \
    Planeacion, Direccion, Organizacion
from datetime import datetime


# Create your views here.


class LoginView(View):
    form = LoginForm()
    message = None
    template = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('mincit:index')
        return render(request, self.template, self.get_contex())

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login_django(request, user)
            return redirect('mincit:index')
        else:
            self.message = 'error, datos incorrectos'

        return render(request, self.template, self.get_contex())

    def get_contex(self):
        return {'form': self.form, 'message': self.message}


class InicioListViews(LoginRequiredMixin, ListView):
    login_url = 'mincit:login'
    model = Empresa
    template_name = 'index.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(InicioListViews, self).get_context_data(
            **kwargs)
        return context


@login_required(login_url='mincit:login')
def logout(request):
    logout_django(request)
    return redirect('mincit:login')


class DiagnosticoEmpresaListViews(LoginRequiredMixin, ListView):
    login_url = 'mincit:login'
    model = DiagnosticoEmpresa
    template_name = 'diagnostico_emp/diagnostico_emp.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(DiagnosticoEmpresaListViews, self).get_context_data(
            **kwargs)
        self.empresa = get_object_or_404(Empresa, id=self.args[0])
        context['id_empresa'] = self.empresa.id
        return context

    def get_queryset(self):
        self.empresa = get_object_or_404(Empresa, id=self.args[0])
        return DiagnosticoEmpresa.objects.filter(id_empresa=self.empresa)


class DiagnosticoEmpresaCreateViews(LoginRequiredMixin, CreateView):
    login_url = 'mincit:login'
    model = DiagnosticoEmpresa
    form_class = DiagnosticoEmpresaForm
    template_name = 'diagnostico_emp/diagnostico_emp_crear.html'
    messages = None
    context = {
        'form': form_class
    }

    def get_context_data(self, **kwargs):
        context = super(DiagnosticoEmpresaCreateViews, self).get_context_data(
            **kwargs)
        empresa = Empresa.objects.get(id=self.args[0])
        fecha = datetime.today()
        asesor = self.request.user.username
        numero = self.get_numero_diagnostico(empresa)
        diagnotico = DiagnosticoEmpresa.objects.create(id_empresa=empresa,
                                                       asesor=asesor,
                                                       fecha=fecha,
                                                       numero_consecutivo=numero)
        context['diag'] = diagnotico
        context['id_diag'] = diagnotico.id
        return context

    def get_numero_diagnostico(self, empresa):
        diagnosticos = DiagnosticoEmpresa.objects.filter(
            id_empresa=empresa).order_by('-id')
        if not diagnosticos:
            return 1
        if diagnosticos is not None:
            diagnostico = diagnosticos[0]
            numero = diagnostico.id
            if numero != None:
                return numero + 1
        return 1


class DiagnosticoEmpresaUpdateViews(LoginRequiredMixin, UpdateView):
    login_url = 'mincit:login'
    model = DiagnosticoEmpresa
    form_class = DiagnosticoEmpresaForm
    template_name = 'diagnostico_emp/diagnostico_emp_editar.html'
    success_url = reverse_lazy('mincit:diganostico_emp')
    slug_field = 'id'
    slug_url_kwarg = 'id_diagnostico'
    messages = None
    context = {
        'form': form_class
    }

    def get_context_data(self, **kwargs):
        context = super(DiagnosticoEmpresaUpdateViews, self).get_context_data(
            **kwargs)
        diagnostico = get_object_or_404(DiagnosticoEmpresa,
                                        id=self.kwargs['id_diagnostico'])
        context['id_diag'] = diagnostico.id
        return context


class InformacionViews(LoginRequiredMixin, View):
    form = InformacionForm
    model = Informacion
    login_url = 'mincit:login'
    messages = None
    template = 'empresa/informacion.html'

    def get(self, request, *args, **kwargs):
        try:
            self.empresa = get_object_or_404(Empresa, id=self.args[0])
            self.informacion = Informacion.objects.get(id_empresa=self.empresa)
            return redirect('mincit:editar_informacion', self.informacion.id)
        except Informacion.DoesNotExist:
            return redirect('mincit:crear_informacion', self.empresa.id)


class InformacionCreateViews(LoginRequiredMixin, CreateView):
    model = Informacion
    form_class = InformacionForm
    template_name = 'empresa/informacion.html'
    success_url = reverse_lazy('mincit:index')
    messages = None
    context = {
        'form': form_class
    }

    def form_valid(self, form):
        empresa = Empresa.objects.get(id=self.args[0])
        form.instance.id_empresa = empresa
        return super(InformacionCreateViews, self).form_valid(form)


class InformacionUpdateViews(LoginRequiredMixin, UpdateView):
    model = Informacion
    form_class = InformacionForm
    template_name = 'empresa/informacion.html'
    success_url = reverse_lazy('mincit:index')
    slug_field = 'id'
    slug_url_kwarg = 'id_informacion'
    messages = None
    context = {
        'form': form_class
    }


class SituacionViews(LoginRequiredMixin, View):
    form = SituacionForm
    model = Situacion
    login_url = 'mincit:login'
    messages = None
    template = 'diagnostico_emp/situacion.html'

    def get(self, request, *args, **kwargs):
        self.diagnostico = get_object_or_404(
            DiagnosticoEmpresa, id=self.kwargs['id_diagnostico'])
        if self.diagnostico.id_situacion is not None:
            return redirect('mincit:editar_situacion',
                            id_situacion=self.diagnostico.id_situacion.id)

        return redirect('mincit:crear_situacion', self.diagnostico.id)


class SituacionCreateViews(LoginRequiredMixin, CreateView):
    model = Situacion
    form_class = SituacionForm
    template_name = 'diagnostico_emp/situacion_crear.html'
    messages = None
    context = {
        'form': form_class
    }
    success_url = None

    def get_success_url(self):
        diagnostico = DiagnosticoEmpresa.objects.get(
            id=self.kwargs['id_diagnostico'])
        url_reverse = "mincit:planeacion"
        try:
            diagnostico.id_situacion = self.object
            diagnostico.save()
        except DiagnosticoEmpresa.DoesNotExist:
            url_reverse = 'mincit:situacion'
        return reverse(
            url_reverse, kwargs={'id_diagnostico': diagnostico.id})


class SituacionUpdateViews(LoginRequiredMixin, UpdateView):
    model = Situacion
    form_class = SituacionForm
    template_name = 'diagnostico_emp/situacion_editar.html'
    success_url = None
    slug_field = 'id'
    slug_url_kwarg = 'id_situacion'
    messages = None
    context = {
        'form': form_class
    }

    def get_success_url(self):
        try:
            situacion = Situacion.objects.get(
                id=self.kwargs['id_situacion'])
            diagnostico = DiagnosticoEmpresa.objects.get(id_situacion=situacion)
            url_reverse = "mincit:planeacion"
        except DiagnosticoEmpresa.DoesNotExist:
            url_reverse = 'mincit:situacion'
        return reverse(
            url_reverse, kwargs={'id_diagnostico': diagnostico.id})


class PlaneacionViews(LoginRequiredMixin, View):
    form = PlaneacionForm
    model = Planeacion
    login_url = 'mincit:login'
    messages = None
    template = 'diagnostico_emp/planeacion.html'

    def get(self, request, *args, **kwargs):
        self.diagnostico = get_object_or_404(DiagnosticoEmpresa,
                                             id=self.kwargs['id_diagnostico'])
        if self.diagnostico.id_planeacion is not None:
            return redirect('mincit:editar_planeacion',
                            id_planeacion=self.diagnostico.id_planeacion.id)

        return redirect('mincit:crear_planeacion', self.diagnostico.id)


class PlaneacionCreateViews(LoginRequiredMixin, CreateView):
    model = Planeacion
    form_class = PlaneacionForm
    template_name = 'diagnostico_emp/planeacion_crear.html'
    messages = None
    context = {
        'form': form_class
    }
    success_url = None

    def get_context_data(self, **kwargs):
        context = super(PlaneacionCreateViews, self).get_context_data(
            **kwargs)

mincit/templates/diagnostico_emp/diagnostico_emp_editar.html
{% extends "plantilla/inicio.html" %}
{% block title %} DIAGNOSTICO_EMP {% endblock %}
{% block contenido %}
<ul class="nav nav-tabs nav-justified">

    <li><a href="{% url 'mincit:situacion' id_diag %}">Situacion</a></li>
    <li><a href="{% url 'mincit:planeacion' id_diag %}">Planeacion</a></li>
    <li><a href="{% url 'mincit:organizacion' id_diag %}">Organizacion</a></li>
    <li><a href="#">Direccion</a></li>
    <li><a href="#">Control</a></li>
    <li><a href="#">Recursos</a></li>
    <li><a href="#">Mercadeo</a></li>
    <li><a href="#">Financiera</a></li>
    <li><a href="#">Produccion</a></li>
    <li><a href="#">Internacionalizacion</a></li>
    <li><a href="#">Aspectos</a></li>
    <li><a href="#">Resumen</a></li>
</ul>
<div class="text-center text-success">
    <h2>
        <b>
            DIAGNÓSTICO DE LA EMPRESA
        </b>
    </h2>
    <div class="h3">
        Programa de Fortalecimiento Empresarial
    </div>
</div>
{% endblock %}

mincit/templates/diagnostico_emp/internacionalizacion.html
{% extends "plantilla/inicio.html" %}
{% block title %} DIAGNOSTICO_EMP {% endblock %}
{% block contenido %}
<ul class="nav nav-tabs nav-justified">
    <li>
        <a href="{% url 'mincit:situacion' id_diagnostico=id_diag %}">Situacion</a>
    </li>
    <li><a href="{% url 'mincit:planeacion' id_diagnostico=id_diag %}">Planeacion</a>
    </li>
    <li><a href="{% url 'mincit:organizacion' id_diagnostico=id_diag %}">Organizacion</a>
    </li>
    <li>
        <a href="{% url 'mincit:direccion' id_diagnostico=id_diag %}">Direccion</a>
    </li>
    <li><a href="{% url 'mincit:control' id_diagnostico=id_diag %}">Control</a>
    </li>
    <li>
        <a href="{% url 'mincit:recursos' id_diagnostico=id_diag %}">Recursos</a>
    </li>
    <li>
        <a href="{% url 'mincit:mercadeo' id_diagnostico=id_diag %}">Mercadeo</a>
    </li>
    <li><a href="{% url 'mincit:financiera' id_diagnostico=id_diag %}">Financiera</a>
    </li>
    <li><a href="{% url 'mincit:produccion' id_diagnostico=id_diag %}">Produccion</a></li>
    <li class="active"><a href="#">Internacionalizacion</a></li>
    <li><a href="#">Aspectos</a></li>
    <li><a href="#">Resumen</a></li>
</ul>
<div class="row">
    <h1 class="text-center text-success">
        <p>
            INTERNACIONALIZACION
        </p>
    </h1>
</div>
<form class="form-horizontal col-xs-12" action="" method="post">
    {% csrf_token %}
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿A qué países ha exportado o importado?:</label>
        <div class="col-sm-4">
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            {{form.paises_exportado_importado}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿A qué mercados ha exportado e importado sus competidores?</label>
        <div class="col-sm-4">
            {{form.mercados_exportado_importado}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿Cuáles son las metas en relación a la exportación e importación?:</label>
        <div class="col-sm-4">
            {{form.metas_relacion}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿Qué estrategia de marketing se requiere para asegurar las ventas de exportación/ importación?:</label>
        <div class="col-sm-4">
            {{form.estrategia_marketing}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿Cuál es el total de ventas esperadas, domésticas y extranjeras, por los próximos tres años?:</label>
        <div class="col-sm-4">
            {{form.total_ventas_esperadas}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿Cuál es el margen comercial para las ventas domésticas / internacionales?:</label>
        <div class="col-sm-4">

            {{form.margen_comercial}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">¿Cuánto capital deberá ser presupuestado para sus proyectos de export/ importación?:</label>
        <div class="col-sm-4">
            {{form.capital_presupuestado}}
        </div>
    </div>
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <button type="submit"
                    class="btn btn-success btn-block btn-flat"> Guardar y
                Enviar
            </button>
        </div><!-- /.col -->
    </div>

</form>
{% endblock %}

mincit/templates/diagnostico_emp/produccion_editar.html
{% extends "plantilla/inicio.html" %}
{% block title %} DIAGNOSTICO_EMP {% endblock %}
{% block contenido %}
<ul class="nav nav-tabs nav-justified">
    <li>
        <a href="{% url 'mincit:situacion' id_diagnostico=id_diag %}">Situacion</a>
    </li>
    <li><a href="{% url 'mincit:planeacion' id_diagnostico=id_diag %}">Planeacion</a>
    </li>
    <li><a href="{% url 'mincit:organizacion' id_diagnostico=id_diag %}">Organizacion</a>
    </li>
    <li>
        <a href="{% url 'mincit:direccion' id_diagnostico=id_diag %}">Direccion</a>
    </li>
    <li><a href="{% url 'mincit:control' id_diagnostico=id_diag %}">Control</a>
    </li>
    <li>
        <a href="{% url 'mincit:recursos' id_diagnostico=id_diag %}">Recursos</a>
    </li>
    <li>
        <a href="{% url 'mincit:mercadeo' id_diagnostico=id_diag %}">Mercadeo</a>
    </li>
    <li><a href="{% url 'mincit:financiera' id_diagnostico=id_diag %}">Financiera</a>
    </li>
    <li class="active"><a href="#">Produccion</a></li>
    <li><a href="#">Internacionalizacion</a></li>
    <li><a href="#">Aspectos</a></li>
    <li><a href="#">Resumen</a></li>
</ul>
<div class="row">
    <h1 class="text-center text-success">
        <p>
            PRODUCCION
        </p>
    </h1>
</div>
<form class="form-horizontal col-xs-12" action="" method="post">
    {% csrf_token %}
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">Conoce el porcentaje de la
            capacidad instalada utilizada de su empresa?
            SI, NO, CUAL ES?:</label>
        <div class="col-sm-4">

            {{form.porcentaje_capacidad}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">Conoce las normas técnicas
            establecidas para el sector?
            SI, NO, CUALES?:</label>
        <div class="col-sm-4">
            {{form.normas_tecnicas}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">Cuál es el estado de maquinaria y
            tecnología de su empresa frente a competitividad?:</label>
        <div class="col-sm-4">
            {{form.estado_maquinaria}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La empresa programa la
            producción:</label>
        <div class="col-sm-4">
            {{form.programa_produccion}}
        </div>
        <label class="col-sm-2 control-label">esta programación responde a la
            demanda del mercado.:</label>
        <div class="col-sm-4">
            {{form.produccion_responde}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La empresa tiene planificación
            financiera formalEn el proceso de producción se definen planes,
            tareas, operaciones, procedimientos y encadenamientos:</label>
        <div class="col-sm-4">

            {{form.proceso_produccion_define}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">Se controla la calidad del
            producto/servicio:</label>
        <div class="col-sm-4">
            {{form.control_calidad}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">Se presentan problemas de
            abastecimiento de materias primas/insumos:</label>
        <div class="col-sm-4">
            {{form.problemas_abastecimiento}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La empresa planea la adquisición
            de maquinaria, tecnología, materia prima, etc:</label>
        <div class="col-sm-4">
            {{form.planea_adquisicion}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La empresa tiene planes de
            contingencia para proveerse de materias primas, recursos humanos,
            etc:</label>
        <div class="col-sm-4">
            {{form.planes_contingencia}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La empresa realiza inventarios
            periódicamente:</label>
        <div class="col-sm-4">
            {{form.realiza_inventarios}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La empresa hace seguimiento a la
            rotación de inventarios:</label>
        <div class="col-sm-4">
            {{form.seguimiento_inventario}}
        </div>
    </div>
    <div class="form-group form-group-s">
        <label class="col-sm-2 control-label">La ubicación y organización de la
            planta permite una eficiente distribución del trabajo:</label>
        <div class="col-sm-4">
            {{form.eficiencia_distribucion}}
        </div>
    </div>

    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <button type="submit"
                    class="btn btn-success btn-block btn-flat"> Guardar y
                Enviar
            </button>
        </div><!-- /.col -->
    </div>

</form>
{% endblock %}