mincit/urls.py
from django.conf.urls import url

from mincit import views

app_name = 'mincit'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^index/$', views.InicioListViews.as_view(), name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^diagnostico_emp/(\d+)/$',
        views.DiagnosticoEmpresaListViews.as_view(),
        name='diagnostico_emp'),
    url(r'^diagnostico_emp/(\d+)/crear/$',
        views.DiagnosticoEmpresaCreateViews.as_view(),
        name='diagnostico_empresa_crear'),
    url(r'^diagnostico_emp/editar/(?P<id_diagnostico>\d+)/$',
        views.DiagnosticoEmpresaUpdateViews.as_view(),
        name='editar_diagnostico'),
    url(r'^diagnostico_emp/informacion/(\d+)/$',
        views.InformacionViews.as_view(),
        name='informacion'),
    url(r'^diagnostico_emp/informacion/crear/(\d+)/$',
        views.InformacionCreateViews.as_view(),
        name='crear_informacion'),
    url(r'^diagnostico_emp/informacion/editar/(?P<id_informacion>\d+)/$',
        views.InformacionUpdateViews.as_view(),
        name='editar_informacion'),
    url(r'^diagnostico_emp/situacion/(?P<id_diagnostico>\d+)/$',
        views.SituacionViews.as_view(),
        name='situacion'),
    url(r'^diagnostico_emp/situacion/crear/(?P<id_diagnostico>\d+)/$',
        views.SituacionCreateViews.as_view(),
        name='crear_situacion'),
    url(r'^diagnostico_emp/situacion/editar/(?P<id_situacion>\d+)/$',
        views.SituacionUpdateViews.as_view(),
        name='editar_situacion'),
    url(r'^diagnostico_emp/planeacion/(?P<id_diagnostico>\d+)/$',
        views.PlaneacionViews.as_view(),
        name='planeacion'),
    url(r'^diagnostico_emp/planeacion/crear/(?P<id_diagnostico>\d+)/$',
        views.PlaneacionCreateViews.as_view(),
        name='crear_planeacion'),
    url(r'^diagnostico_emp/planeacion/editar/(?P<id_planeacion>\d+)/$',
        views.PlaneacionUpdateViews.as_view(),
        name='editar_planeacion'),
    url(r'^diagnostico_emp/organizacion/(?P<id_diagnostico>\d+)/$',
        views.OrganizacionViews.as_view(),
        name='organizacion'),
    url(r'^diagnostico_emp/organizacion/crear/(?P<id_diagnostico>\d+)/$',
        views.OrganizacionCreateViews.as_view(),
        name='crear_organizacion'),
    url(r'^diagnostico_emp/organizacion/editar/(?P<id_organizacion>\d+)/$',
        views.OrganizacionUpdateViews.as_view(),
        name='editar_organizacion'),
    url(r'^diagnostico_emp/direccion/(?P<id_diagnostico>\d+)/$',
        views.DireccionViews.as_view(),
        name='direccion'),
    url(r'^diagnostico_emp/direccion/crear/(?P<id_diagnostico>\d+)/$',
        views.DireccionCreateViews.as_view(),
        name='crear_direccion'),
    url(r'^diagnostico_emp/direccion/editar/(?P<id_direccion>\d+)/$',
        views.DireccionUpdateViews.as_view(),
        name='editar_direccion'),
    url(r'^diagnostico_emp/control/(?P<id_diagnostico>\d+)/$',
        views.ControlViews.as_view(),
        name='control'),
    url(r'^diagnostico_emp/control/crear/(?P<id_diagnostico>\d+)/$',
        views.ControlCreateViews.as_view(),
        name='crear_control'),
    url(r'^diagnostico_emp/control/editar/(?P<id_control>\d+)/$',
        views.ControlUpdateViews.as_view(),
        name='editar_control'),
    url(r'^diagnostico_emp/recursos/(?P<id_diagnostico>\d+)/$',
        views.RecursoViews.as_view(),
        name='recursos'),
    url(r'^diagnostico_emp/recursos/crear/(?P<id_diagnostico>\d+)/$',
        views.RecursoCreateViews.as_view(),
        name='crear_recursos'),
    url(r'^diagnostico_emp/recursos/editar/(?P<id_recurso>\d+)/$',
        views.RecursoUpdateViews.as_view(),
        name='editar_recursos'),
    url(r'^diagnostico_emp/mercadeo/(?P<id_diagnostico>\d+)/$',
        views.MercadeoViews.as_view(),
        name='mercadeo'),
    url(r'^diagnostico_emp/mercadeo/crear/(?P<id_diagnostico>\d+)/$',
        views.MercadeoCreateViews.as_view(),
        name='crear_mercadeo'),
    url(r'^diagnostico_emp/mercadeo/editar/(?P<id_mercadeo>\d+)/$',
        views.MercadeoUpdateViews.as_view(),
        name='editar_mercadeo'),
    url(r'^diagnostico_emp/financiera/(?P<id_diagnostico>\d+)/$',
        views.FinancieraViews.as_view(),
        name='financiera'),
    url(r'^diagnostico_emp/financiera/crear/(?P<id_diagnostico>\d+)/$',
        views.FinancieraCreateViews.as_view(),
        name='crear_financiera'),
    url(r'^diagnostico_emp/financiera/editar/(?P<id_financiera>\d+)/$',
        views.FinancieraUpdateViews.as_view(),
        name='editar_financiera'),
    url(r'^diagnostico_emp/produccion/(?P<id_diagnostico>\d+)/$',
        views.ProduccionViews.as_view(),
        name='produccion'),
    url(r'^diagnostico_emp/produccion/crear/(?P<id_diagnostico>\d+)/$',
        views.ProduccionCreateViews.as_view(),
        name='crear_produccion'),
    url(r'^diagnostico_emp/produccion/editar/(?P<id_produccion>\d+)/$',
        views.ProduccionUpdateViews.as_view(),
        name='editar_produccion'),
    url(r'^diagnostico_emp/internacionalizacion/(?P<id_diagnostico>\d+)/$',
        views.InternacionalizacionViews.as_view(),
        name='internacionalizacion'),
    url(r'^diagnostico_emp/internacionalizacion/crear/(?P<id_diagnostico>\d+)/$',
        views.InternacionalizacionCreateViews.as_view(),
        name='crear_internacionalizacion'),
    url(r'^diagnostico_emp/internacionalizacion/editar/(?P<id_internacionalizacion>\d+)/$',
        views.InternacionalizacionUpdateViews.as_view(),
        name='editar_internacionalizacion'),


]

urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^mincit/', include('mincit.urls')),

]

mincit/views.py
from __future__ import print_function
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import response
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls.base import reverse
from django.views.generic import View, CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from mincit.forms import LoginForm, InformacionForm, SituacionForm, \
    PlaneacionForm, DiagnosticoEmpresaForm, \
    OrganizacionForm, DireccionForm, ControlForm, RecursoForm, FinancieraForm, \
    MercadeoForm, ProduccionForm, InternacionalizacionForm
from mincit.models import Control, Recurso, Financiera, Mercadeo, Produccion, \
    Internacionalizacion
from models import Empresa, Informacion, DiagnosticoEmpresa, Situacion, \
    Planeacion, Direccion, Organizacion
from datetime import datetime


# Create your views here.


class LoginView(View):
    form = LoginForm()
    message = None
    template = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('mincit:index')
        return render(request, self.template, self.get_contex())

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login_django(request, user)
            return redirect('mincit:index')
        else:
            self.message = 'error, datos incorrectos'

        return render(request, self.template, self.get_contex())

    def get_contex(self):
        return {'form': self.form, 'message': self.message}


class InicioListViews(LoginRequiredMixin, ListView):
    login_url = 'mincit:login'
    model = Empresa
    template_name = 'index.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(InicioListViews, self).get_context_data(
            **kwargs)
        return context


@login_required(login_url='mincit:login')
def logout(request):
    logout_django(request)
    return redirect('mincit:login')


class DiagnosticoEmpresaListViews(LoginRequiredMixin, ListView):
    login_url = 'mincit:login'
    model = DiagnosticoEmpresa
    template_name = 'diagnostico_emp/diagnostico_emp.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(DiagnosticoEmpresaListViews, self).get_context_data(
            **kwargs)
        self.empresa = get_object_or_404(Empresa, id=self.args[0])
        context['id_empresa'] = self.empresa.id
        return context

    def get_queryset(self):
        self.empresa = get_object_or_404(Empresa, id=self.args[0])
        return DiagnosticoEmpresa.objects.filter(id_empresa=self.empresa)


class DiagnosticoEmpresaCreateViews(LoginRequiredMixin, CreateView):
    login_url = 'mincit:login'
    model = DiagnosticoEmpresa
    form_class = DiagnosticoEmpresaForm
    template_name = 'diagnostico_emp/diagnostico_emp_crear.html'
    messages = None
    context = {
        'form': form_class
    }

    def get_context_data(self, **kwargs):
        context = super(DiagnosticoEmpresaCreateViews, self).get_context_data(
            **kwargs)
        empresa = Empresa.objects.get(id=self.args[0])
        fecha = datetime.today()
        asesor = self.request.user.username
        numero = self.get_numero_diagnostico(empresa)
        diagnotico = DiagnosticoEmpresa.objects.create(id_empresa=empresa,
                                                       asesor=asesor,
                                                       fecha=fecha,
                                                       numero_consecutivo=numero)
        context['diag'] = diagnotico
        context['id_diag'] = diagnotico.id
        return context

    def get_numero_diagnostico(self, empresa):
        diagnosticos = DiagnosticoEmpresa.objects.filter(
            id_empresa=empresa).order_by('-id')
        if not diagnosticos:
            return 1
        if diagnosticos is not None:
            diagnostico = diagnosticos[0]
            numero = diagnostico.id
            if numero != None:
                return numero + 1
        return 1


class DiagnosticoEmpresaUpdateViews(LoginRequiredMixin, UpdateView):
    login_url = 'mincit:login'
    model = DiagnosticoEmpresa
    form_class = DiagnosticoEmpresaForm
    template_name = 'diagnostico_emp/diagnostico_emp_editar.html'
    success_url = reverse_lazy('mincit:diganostico_emp')
    slug_field = 'id'
    slug_url_kwarg = 'id_diagnostico'
    messages = None
    context = {
        'form': form_class
    }

    def get_context_data(self, **kwargs):
        context = super(DiagnosticoEmpresaUpdateViews, self).get_context_data(
            **kwargs)
        diagnostico = get_object_or_404(DiagnosticoEmpresa,
                                        id=self.kwargs['id_diagnostico'])
        context['id_diag'] = diagnostico.id
        return context


class InformacionViews(LoginRequiredMixin, View):
    form = InformacionForm
    model = Informacion
    login_url = 'mincit:login'
    messages = None
    template = 'empresa/informacion.html'

    def get(self, request, *args, **kwargs):
        try:
            self.empresa = get_object_or_404(Empresa, id=self.args[0])
            self.informacion = Informacion.objects.get(id_empresa=self.empresa)
            return redirect('mincit:editar_informacion', self.informacion.id)
        except Informacion.DoesNotExist:
            return redirect('mincit:crear_informacion', self.empresa.id)


class InformacionCreateViews(LoginRequiredMixin, CreateView):
    model = Informacion
    form_class = InformacionForm
    template_name = 'empresa/informacion.html'
    success_url = reverse_lazy('mincit:index')
    messages = None
    context = {
        'form': form_class
    }

    def form_valid(self, form):
        empresa = Empresa.objects.get(id=self.args[0])
        form.instance.id_empresa = empresa
        return super(InformacionCreateViews, self).form_valid(form)


class InformacionUpdateViews(LoginRequiredMixin, UpdateView):
    model = Informacion
    form_class = InformacionForm
    template_name = 'empresa/informacion.html'
    success_url = reverse_lazy('mincit:index')
    slug_field = 'id'
    slug_url_kwarg = 'id_informacion'
    messages = None
    context = {
        'form': form_class
    }


class SituacionViews(LoginRequiredMixin, View):
    form = SituacionForm
    model = Situacion
    login_url = 'mincit:login'
    messages = None
    template = 'diagnostico_emp/situacion.html'

    def get(self, request, *args, **kwargs):
        self.diagnostico = get_object_or_404(
            DiagnosticoEmpresa, id=self.kwargs['id_diagnostico'])
        if self.diagnostico.id_situacion is not None:
            return redirect('mincit:editar_situacion',
                            id_situacion=self.diagnostico.id_situacion.id)

        return redirect('mincit:crear_situacion', self.diagnostico.id)


class SituacionCreateViews(LoginRequiredMixin, CreateView):
    model = Situacion
    form_class = SituacionForm
    template_name = 'diagnostico_emp/situacion_crear.html'
    messages = None
    context = {
        'form': form_class
    }
    success_url = None

    def get_success_url(self):
        diagnostico = DiagnosticoEmpresa.objects.get(
            id=self.kwargs['id_diagnostico'])
        url_reverse = "mincit:planeacion"
        try:
            diagnostico.id_situacion = self.object
            diagnostico.save()
        except DiagnosticoEmpresa.DoesNotExist:
            url_reverse = 'mincit:situacion'
        return reverse(
            url_reverse, kwargs={'id_diagnostico': diagnostico.id})


class SituacionUpdateViews(LoginRequiredMixin, UpdateView):
    model = Situacion
    form_class = SituacionForm
    template_name = 'diagnostico_emp/situacion_editar.html'
    success_url = None
    slug_field = 'id'
    slug_url_kwarg = 'id_situacion'
    messages = None
    context = {
        'form': form_class
    }

    def get_success_url(self):
        try:
            situacion = Situacion.objects.get(
                id=self.kwargs['id_situacion'])
            diagnostico = DiagnosticoEmpresa.objects.get(id_situacion=situacion)
            url_reverse = "mincit:planeacion"
        except DiagnosticoEmpresa.DoesNotExist:
            url_reverse = 'mincit:situacion'
        return reverse(
            url_reverse, kwargs={'id_diagnostico': diagnostico.id})


class PlaneacionViews(LoginRequiredMixin, View):
    form = PlaneacionForm
    model = Planeacion
    login_url = 'mincit:login'
    messages = None
    template = 'diagnostico_emp/planeacion.html'

    def get(self, request, *args, **kwargs):
        self.diagnostico = get_object_or_404(DiagnosticoEmpresa,
                                             id=self.kwargs['id_diagnostico'])
        if self.diagnostico.id_planeacion is not None:
            return redirect('mincit:editar_planeacion',
                            id_planeacion=self.diagnostico.id_planeacion.id)

        return redirect('mincit:crear_planeacion', self.diagnostico.id)


class PlaneacionCreateViews(LoginRequiredMixin, CreateView):
    model = Planeacion
    form_class = PlaneacionForm
    template_name = 'diagnostico_emp/planeacion_crear.html'
    messages = None
    context = {
        'form': form_class
    }
    success_url = None

    def get_context_data(self, **kwargs):
        context = super(PlaneacionCreateViews, self).get_context_data(
            **kwargs)

mincit/templates/Home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MinCit|Index</title>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="Elastic Image Slideshow with Thumbnail Preview"/>
    <meta name="keywords"
          content="jquery, css3, responsive, image, slider, slideshow, thumbnails, preview, elastic"/>
    <meta name="author" content="Codrops"/>
    <link rel="shortcut icon" href="../favicon.ico">
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css"
          rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'css/AdminLTE.min.css' %}" type="text/css"
          rel="stylesheet" media="screen,projection"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'slider/css/demo.css'%}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'slider/css/style.css' %}"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic'
          rel='stylesheet' type='text/css'/>
    <noscript>
        <link rel="stylesheet" type="text/css"
              href="{% static 'slider/css/noscript.css' %}"/>
    </noscript>

</head>
<body>
<div class="container">
    <div class="header">

        <div class="clr"></div>
    </div>
    <div>

        <img src="{% static 'img/logo.jpg' %}" class="imagen-responsive" alt="">
    </div>

    <div class="wrapper">
        <div id="ei-slider" class="ei-slider">
            <ul class="ei-slider-large">
                <li>
                    <a href="http://www.mincit.gov.co/publicaciones.php?id=37099">
                        <img src="{% static 'img/publicacion1.jpg' %}"
                             alt="image06"/>
                        <div class="ei-title">
                            <h2>Colombia etc</h2>
                            <h3>aqui va la info</h3>
                        </div>
                    </a>
                </li>
                <li>
                    <img src="slider/images/large/1.jpg" alt="image01"/>
                    <div class="ei-title">
                        <h2>Creative</h2>
                        <h3>Duet</h3>
                    </div>
                </li>
                <li>
                    <img src="slider/images/large/2.jpg" alt="image02"/>
                    <div class="ei-title">
                        <h2>Friendly</h2>
                        <h3>Devil</h3>
                    </div>
                </li>
                <li>
                    <img src="slider/images/large/3.jpg" alt="image03"/>
                    <div class="ei-title">
                        <h2>Tranquilent</h2>
                        <h3>Compatriot</h3>
                    </div>
                </li>

            </ul><!-- ei-slider-large -->
            <ul class="ei-slider-thumbs">
                <li class="ei-slider-element">Current</li>
                <li><a href="#">Slide 6</a><img
                        src="{% static 'img/publicacion1.jpg' %}"
                        alt="thumb06"/></li>
                <li><a href="#">Slide 1</a><img src="slider/images/thumbs/1.jpg"
                                                alt="thumb01"/></li>
                <li><a href="#">Slide 2</a><img src="slider/images/thumbs/2.jpg"
                                                alt="thumb02"/></li>
                <li><a href="#">Slide 3</a><img src="slider/images/thumbs/3.jpg"
                                                alt="thumb03"/></li>
            </ul><!-- ei-slider-thumbs -->
        </div><!-- ei-slider -->
        <br />
    </div><!-- wrapper -->

    <div class="row">
        <div class="col-md-4 col-xs-12 col-md-offset-4 text-center">
            <a href="{% url 'mincit:login' %}" class="btn btn-success btn-block btn-flat">
                Log In
            </a>
        </div><!-- /.col -->
    </div>

    <!----foorter------>
    <div class="row">
        <hr>
        <div class="col-lg-12">
            <div class="col-md-8">
                <a href="#">Desarrollado por:</a> | <a href="">Mayerly
                Garcia </a>
            </div>
            <div class="col-md-4">
                <p class="muted pull-right">© 2016 Compañia. Todos los derechos
                    reservados</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript"
        src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript"
        src="{% static 'slider/js/jquery.eislideshow.js' %}"></script>
<script type="text/javascript"
        src="{% static 'slider/js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript"
        src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script type="text/javascript">
            $(function() {
                $('#ei-slider').eislideshow({
					animation			: 'center',
					autoplay			: true,
					slideshow_interval	: 3000,
					titlesFactor		: 0
                });
            });

</script>
</body>
</html>

mincit/templates/index.html
{% extends "plantilla/inicio.html" %}
{% block title %} Incio {% endblock %}
{% block contenido %}
<h1 class="text-center"><b>Empresas Registradas</b></h1>
{% if object_list %}
    <div class="col-md-8 col-md-offset-2 text-center">
        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Nit</th>
                    <th class="text-center">Opciones</th>
                    <th class="text-center">Registros</th>
            </thead>
            <tbody>
            {% for emp in object_list %}
                <tr>
                    <td>{{ emp.id }}</td>
                    <td>{{ emp.nombre }}</td>
                    <td>{{ emp.nit }}</td>
                    <td>
                         <a class="btn btn-default btn-xs" title="Informacion"
                           data-toggle="tooltip" data-placement="top"
                            href="{% url 'mincit:informacion' emp.id %}">
                            <i class="fa fa-edit">Editar Informacion</i>
                        </a>
                    </td>

                    <td>
                        <a class="btn btn-default btn-xs" title="Diagnostico Emp"
                           data-toggle="tooltip" data-placement="top"
                            href="{% url 'mincit:diagnostico_emp' emp.id %}">
                            <i class="fa fa-search">Diagnostico_Emp</i>
                        </a>
                        <a class="btn btn-default btn-xs" title="Plan Accion"
                           data-toggle="tooltip" data-placement="top"
                            href="">
                            <i class="fa fa-search">Plan_Accion</i>
                        </a>
                        <a class="btn btn-default btn-xs" title="Diagnostico Idea"
                           data-toggle="tooltip" data-placement="top"
                            href="">
                            <i class="fa fa-search">Diagnostico_Idea</i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% include 'plantilla/pagination.html' %}

    {% else %}
        <h3 class="text-info">No se han registrado empresas.</h3>
    {% endif %}

    </div>
{% endblock %}

mincit/templates/inicio.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
          name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css"
          rel="stylesheet"
          media="screen,projection"/>

    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet"
          href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link href="{% static 'css/AdminLTE.min.css' %}" type="text/css"
          rel="stylesheet"
          media="screen,projection"/>
    <link href="{% static 'css/app.css' %}" type="text/css" rel="stylesheet"
          media="screen,projection"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <img src="{% static 'img/prueba.png' %}" class="image-responsive"
                 alt="">
        </div>
        <ul class="nav navbar-nav">
            <li><a href="">Home</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Registros <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'mincit:diagnostico_emp' %}">Diagnostico
                        de la Empresa</a></li>
                    <li><a href="registro/plan_accion/plan_accion.html">Plan de
                        accion</a></li>
                    <li>
                        <a href="registro/diagnostico_eval/diagnostico_eval.html">Diagnostico
                            de evaluacion</a></li>
                    <li class="divider"></li>
                    <li><a href="registro/logros.html">Logros</a></li>
                </ul>
            </li>
            <li><a href="consultas/consulta.html">Consultas</a></li>
            <li><a href="configuracion/configuracion.html">Configuracion</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span>
                Perfil</a></li>
            <li><a href="{% url 'mincit:logout' %}"><span
                    class="glyphicon glyphicon-log-in"></span> Salir</a></li>
        </ul>
    </div>
</nav>
{% block contenido%}
{% endblock %}
<div class="row">
    <hr>
    <div class="col-lg-12">
        <div class="col-md-8">
            <a href="#">Desarrollado por:</a> | <a href="">Mayerly Garcia</a>
        </div>
        <div class="col-md-4">
            <p class="muted pull-right">© 2016 Compañia. Todos los derechos
                reservados</p>
        </div>
    </div>
</div>
<script src="{% static 'plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

mincit/templates/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>registro Usuario</title>
</head>
<body>

</body>
</html>